# Generated by Django 5.1.3 on 2024-11-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(blank=True, max_length=100, null=True)),
                ('destino', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('fecha_llegada', models.DateField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('hora_llegada', models.TimeField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
