# Generated by Django 5.1.3 on 2024-11-26 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=10, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('clase', models.CharField(blank=True, max_length=100, null=True)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelos_api.avion')),
            ],
        ),
    ]
