# Generated by Django 5.1.3 on 2024-11-26 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_aeropuerto', '0001_initial'),
        ('vuelos_api', '0002_avion_asiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vuelo',
            old_name='capacidad',
            new_name='duracion',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='disponible',
        ),
        migrations.AddField(
            model_name='vuelo',
            name='avion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vuelos_api.avion'),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='avion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vuelos_api.avion'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_destino', to='api_aeropuerto.aeropuerto'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_origen', to='api_aeropuerto.aeropuerto'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
