# Generated by Django 5.1.3 on 2024-11-26 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_api', '0002_alter_user_apellido_alter_user_correo_and_more'),
        ('vuelos_api', '0003_rename_capacidad_vuelo_duracion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.user')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelos_api.vuelo')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('metodo', models.CharField(max_length=50)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_api.reserva')),
            ],
        ),
    ]
