# Generated by Django 5.1.3 on 2024-11-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_alter_user_apellido_alter_user_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
